version: "3.9"
   
services:
  web:
    build: .
    container_name: clinical_trial
    command: bash -c "
      python manage.py runserver 0.0.0.0:8006 --settings=POCClinicalTrial.settings.dev
      "
    volumes:
      - .:/code
    ports:
      - "8006:8006"

